Updated reboot state

diff --git a/nagios/check_debian_packages b/nagios/check_debian_packages
--- a/nagios/check_debian_packages
+++ b/nagios/check_debian_packages
@@ -14,7 +14,8 @@ fi
 
 if [ -f /var/run/reboot-required ]
 then
-	exit 1
+	echo "Reboot required"
+	exit 2
 fi
 
 echo "OK: packages up-to-date"
